from Uniandes_Framework.delphes_reader.particle.electron_particle import ElectronParticle
from Uniandes_Framework.delphes_reader.particle.jet_particle import JetParticle
from Uniandes_Framework.delphes_reader.particle.met_particle import MetParticle
from Uniandes_Framework.delphes_reader.particle.muon_particle import MuonParticle